#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Automated Essay Scoring: A Data-First Deep Learning Approach                        #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.4                                                                              #
# Filename   : /fp2022.yml                                                                         #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/AutomatedEssayScoring                              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Tuesday August 16th 2022 04:17:54 am                                                #
# Modified   : Wednesday August 17th 2022 12:23:40 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : BSD 3-clause "New" or "Revised" License                                             #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
---

name: fp2022_data_etl
steps:
    1:
        name: data_download_api
        module: atelier.workflow.operators
        operator: KaggleDownloader
        params:
            competition: feedback-prize-effectiveness
            destination: data/fp2022/external
            filename: feedback-prize-effectiveness.zip
            force: False
    2:
        name: data_extract_zip
        module: atelier.workflow.operators
        operator: ExtractZip
        params:
            source: data/fp2022/external/feedback-prize-effectiveness.zip
            destination: data/fp2022/raw
            force: False
    3:
        name: load_data_csv
        module: atelier.workflow.operators
        operator: LoadCSV
        params:
            filepath: data/fp2022/raw/train.csv
            encoding: 'utf-8'
            encoding_errors: 'strict'
            force: False
    4:
        name: save_data_parquet
        module: atelier.workflow.operators
        operator: SaveParquet
        params:
            filepath: data/fp2022/staged/train.parquet
            force: True
...